### PR TITLE
Refactor and Integration Tests

### PR DESCRIPTION
**Pull request by ZackBotkin**
This is the refactor and the integration tests.

It's my branch "hack-hack", which itself contains the branch "hack".

I don't expect this to pass on the first go because I need to integrate with travis, but I wasn't sure how to do that, so I'm just getting my work out there while I'm figuring things out.

### CODE REVIEW

**Comment by ZackBotkin** [comment]
Also, a few more things.

1) I am working on converting the postgresql test to behave. Once done, all of the integration tests will be behave-ified (lol), and we can hopefully add these to travis build.

2) I got rid of most/all of the unit testing, because right now I don't feel we really need any unit testing. Typically when you unit test, you mock out anything that interacts with an outside system. Since the entire project at this point is interacting with outside systems (the databases), it doesn't make sense to really have them. Once our logic gets more complex, we can mock out database calls and test only the logic, but right now, it felt like overkill to test what is basically a database read.

**Comment by Harlekuin** [comment]
That's a good point re the unit tests - definitely not as important (and just a waste of time) compared to integration tests

**Comment by Harlekuin** [comment]
Also, I'll have access to a PC soon too so I can start getting your awesome upgrades in!

**Comment by Harlekuin** [comment]
Have a look at the other PR - there are a few changes there you might want to pull in before doing too much more on the behave front.

Also, this is now related to #36, just to keep everything nice and clean

**Comment by Harlekuin** [comment]
looking through the Behave stuff you've done - it's looking really nice. Do you intend for it to replace all the other integration tests out of interest?

Also - the integration tests for postgresql are working on your hack branch at the moment, if it's not working for you on travis or w/e then check out the integration test there for clues perhaps.

**Comment by ZackBotkin** [comment]
> looking through the Behave stuff you've done - it's looking really nice. Do you intend for it to replace all the other integration tests out of interest?
> 
> Also - the integration tests for postgresql are working on your hack branch at the moment, if it's not working for you on travis or w/e then check out the integration test there for clues perhaps.

I intent to completely replace all regression/integration tests we have going on with behave. Once we have some common functionality defined in the Python scripts, it then becomes very easy to write tests for any case that might pop up. Also we can integrate it with some visual dashboard type stuff (look up testrail if you are interested), but that's kind of thinking ahead at this point.

**Comment by Harlekuin** [comment]
Cool. Lets just focus on the behave tests then and getting those to 100% coverage, and then removing the existing tests.

We should get the other PR merged first, and then merge the changes into this branch once that is done so we're not making changes here on old code. I'm happy to merge the changes into this one and go through the merge conflicts if you like as I've got a pretty good idea of what is going on now that I've commited a whole bunch to the hack branch on. I won't touch the behave stuff, which I assume will break after the merge and will need some updating.

**Comment by Harlekuin** [comment]
Also re. testrail - I'm a huge fan of new technologies so happy to look at that in the future. I didn't look into it that closely - is it free for open source?

**Comment by ZackBotkin** [comment]
Hopefully you won't have to fix too many merge conflicts. I pulled down the version of "hack" which should now be updated with your changes. I'll rebase on top of that, and then push up the "hack-hack" (now with your changes underneath), and then we should be good to go.

**Comment by ZackBotkin** [comment]
I got all 3 integration tests working end to end and pushed the code. It looks like there's still 2 merge conflicts, hopefully they aren't hard to fix.

Right now, the tests setup/teardown logic is very specific to my box, and uses the executables included with the databases to drop any existing tables before we run the tests. This will have to change to be more universal, or at least made to work on the box that travis runs the tests on. Look at the fixtures.py file, you will see what I mean.

**Comment by Harlekuin** [comment]
I can give it a go - I didn't bother running Travis locally because you can squash commits later anyway.

Also it of interest, are you using poetry/a virtual env when running these tests? I don't think you have to worry about PYTHONPATH if so

**Comment by Harlekuin** [comment]
the "hack" branch was fully merged into dev so you can just pull from there now and delete "hack" if you like

**Comment by Harlekuin** [comment]
Alrighty - I checked out hack-hack, made a branch from it on my project (branch: test-behave) and merged dev into it. Just so I could get my head around it I cut it down to the bare bones of testing creating a table and a record.

Anyway, behave is fantastic! I'm loving it and it makes so much sense for this project. It worked almost immediately using the travis services for mysql and postgresql (check out build https://travis-ci.org/Harlekuin/SimQLe/jobs/543613154 and coverage https://codecov.io/gh/Harlekuin/SimQLe/branch/test-behave)

You can run travis locally using docker, but I would recommend just committing and pushing all your changes and seeing if the PR passes the tests or not. We will squash the commits anyway and would save you the hassle of having to set up anything locally.

I'll add the other tests to behave, including some basic general unit tests etc to get the coverage back to 100%. If you like I can push to this branch as well given all 3 databases are working nicely.

**Comment by Harlekuin** [comment]
also i moved features/ to the top level of the repo -  I think that is what is recommended by behave (and also behave itself does that)

**Comment by ZackBotkin** [comment]
> I can give it a go - I didn't bother running Travis locally because you can squash commits later anyway.
> 
> Also it of interest, are you using poetry/a virtual env when running these tests? I don't think you have to worry about PYTHONPATH if so

I am using virtualenv to run everything.  I've got a virtual environment that I just run a bunch of pip installs inside, until your code worked haha.

Glad you like behave. I think it's pretty cool too. Nice how you can just describe a test in basic English once the python is written. Your changes with moving the features/ to the top level sounds fine. It's also great that you were able to get it integrated into Travis so quickly. That's cool to see.

One last thing... my real job is picking up for end of quarter deadlines. Might not be able to push much more than a few quick fixes/tests through the next week.

**Comment by Harlekuin** [comment]
I got the tests to 100% coverage using behave in PR #37, so I can close this one. I based the branch used in that one off your hack-hack branch.

I'll update the version and get the latest into pypi. Thanks for all your help on this one!

**Comment by Harlekuin** [comment]
now 0.3.0 live and uploaded to pypi!

**Pull request closed without merging**
